# Generated by Django 5.2.7 on 2025-10-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_carrinho_carrinhoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinhoitem',
            old_name='roduto',
            new_name='produto',
        ),
    ]
